stages:
- package
- build

package:
  before_script:
  - echo "MAVEN_OPTS=\"-Djavax.net.ssl.trustStore=truststore.pem -Djavax.net.ssl.trustStorePassword=123456\"" > ~/.mavenrc
  - mkdir -p /root/.m2
  - cp settings.xml /root/.m2/settings.xml
  stage: package
  image: dock.gaikai.org/htonnies/lein:2.8.1
  script:
  - lein uberjar
  artifacts:
    paths:
    - target/clj-kstream-hh.jar
  tags:
  - ait1-dev

build:
  dependencies:
  - package
  stage: build
  image:
    name: dock.gaikai.org/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
  - mv target/clj-kstream-hh.jar deploy/
  script:
  - echo "{\"auths\":{\"wharf.gaikai.org\":{\"username\":\"$wharf_user\",\"password\":\"$wharf_token\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/deploy/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
  - tags
  tags:
  - ci
  - docker

